project:
  type: website
  output-dir: docs

website:
  title: "CamGit12.github.io"
  favicon: ram.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: CV.qmd
        text: Resume
      - href: Projects.qmd
        text: Projects
  page-footer:
    left: "© 2025 Cameron McLaughlin"
    right: "Built with [Quarto](https://quarto.org/)"

format:
  html:
    theme: cosmo
    css: styles.scss
    toc: true

editor: visual

