project:
  type: website
  output-dir: docs

website:
  title: "Cameron McLaughlin"
  favicon: ram.ico
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: Resume.qmd
        text: My Resume
      - href: Projects.qmd
        text: Research & Projects
  page-footer:
    left: "© 2025 Cameron McLaughlin"
    right: "Built with [Quarto](https://quarto.org/)"

format:
  html:
    theme: cosmo
    css: styles.scss
    toc: true

editor: visual

